version: "3.9"
services:
    web:
        build: .
        ports:
            - 8000:8000
        command: ./manage.py runserver 0.0.0.0:8000
        depends_on: 
            - postgres
            - web-migration
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432

    web-migration:
        build: .
        command: ./manage.py migrate
        depends_on:
            - postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
    postgres:
        image: postgres:13-alpine
        
        ports: 
            - 5432:5432
        #volumes:
        #    - postgres_data:/var/lib/postgresql/data:rw/
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
#volumes:
#    postgres_data:
