

version: "3.9"
services:
    web:
        build: .
        ports:
            - 8000:8000
        command: ./manage.py runserver 0.0.0.0:8000
        depends_on:
            - postgres
            - elasticsearch
            - web-migration
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432

    web-migration:
        build: .
        command: ./manage.py migrate
        depends_on:
            - postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432

    postgres:
        image: postgres:13-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        volumes:
             - db:/var/lib/postgresql/data

    redis:
        image: redis:7.0.6-alpine
        ports:
            - 6379:6379

    rabbitmq:
        image: rabbitmq:3.11.4-alpine
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
            - RABBITMQ_DEFAULT_VHOST=my_vhost

    elasticsearch:
        image: elasticsearch:7.17.8
        ports:
            - 9200:9200
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node

    model_index:
        build: .
        command: ./manage.py search_index --rebuild
        depends_on:
            - elasticsearch
            - web-migration

    worker:
        image: worker
        build:
            context: .
            dockerfile: worker.Dockerfile
        working_dir: /src
        command: ["celery", "-A", "socialnews", "worker"]
        depends_on:
            - rabbitmq
        environment:
            - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672/my_vhost
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        volumes:
            - /home/mputo/socialnews/models:/models

    flower:
        image: flower
        build:
            context: .
            dockerfile: flower.Dockerfile
        command: ["celery", "flower", "--port=5566"]
        ports:
            - 5566:5566
        depends_on:
            - worker
            - rabbitmq
        environment:
            - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672/my_vhost
volumes:
    bart-mnli:
        external: true
    db:
        driver: local