name: Build my app
on: [push]
jobs:
  build-app:
    timeout-minutes: 18
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Install dependencies
          run: pip install -r requirements.txt
        
        - name: Create volume BART-mnli
          run: docker volume create --name=bart-mnli

        - name: Docker compose
          run: DOCKER_BUILDKIT=1 docker-compose up --build -d

        - name: Run tests
          run: src/manage.py test

        - name: Stop containers
          if: always()
          run: docker-compose down