name: Build my app
on: [push]
jobs:
  build-app:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Install dependencies
          run: pip install -r requirements.txt
        
        - name: Docker compose
          run: DOCKER_BUILDKIT=1 docker-compose up --build